
# Image URL to use all building/pushing image targets
IMG ?= controller:latest
# Produce CRDs that work back to Kubernetes 1.11 (no version conversion)
CRD_OPTIONS ?= "crd:trivialVersions=true"

# Get the currently used golang install path (in GOPATH/bin, unless GOBIN is set)
ifeq (,$(shell go env GOBIN))
GOBIN=$(shell go env GOPATH)/bin
else
GOBIN=$(shell go env GOBIN)
endif

all: manager

# Run tests
# test: generate fmt vet manifests
#	go test ./controllers/... ./issuers/... -coverprofile cover.out

# Setting SHELL to bash allows bash commands to be executed by recipes.
# This is a requirement for 'setup-envtest.sh' in the test target.
# Options are set to exit when a recipe line exits non-zero or a piped command fails.
SHELL = /usr/bin/env bash -o pipefail
.SHELLFLAGS = -ec

ENVTEST_ASSETS_DIR=$(shell pwd)/testbin
test: manifests generate fmt vet ## Run tests.
	mkdir -p ${ENVTEST_ASSETS_DIR}
	test -f ${ENVTEST_ASSETS_DIR}/setup-envtest.sh || curl -sSLo ${ENVTEST_ASSETS_DIR}/setup-envtest.sh https://raw.githubusercontent.com/kubernetes-sigs/controller-runtime/v0.8.3/hack/setup-envtest.sh
	source ${ENVTEST_ASSETS_DIR}/setup-envtest.sh; fetch_envtest_tools $(ENVTEST_ASSETS_DIR); setup_envtest_env $(ENVTEST_ASSETS_DIR); go test ./... -coverprofile cover.out


# e2e tests (requires simulator, see sim target)
teste2e: 
	go test ./test/... -coverprofile cover.out

# Build manager binary
manager: generate fmt vet
	go build -ldflags="-X 'main.version=$(shell git describe --tags)' -X 'main.buildTime=$(shell date)'" -o bin/manager main.go

# Run against the configured Kubernetes cluster in ~/.kube/config
run: generate fmt vet manifests
	go run ./main.go

# Uninstall CRDs from a cluster
uninstall: 
	kustomize build config/crd | kubectl delete -f -

# Install CRDs into a cluster
install:
	kustomize build config/crd | kubectl apply -f -

# Deploy controller in the configured Kubernetes cluster in ~/.kube/config
deploy:
	cd config/manager && kustomize edit set image controller=${IMG}
	kustomize build config/default | kubectl apply -f -

# Generate manifests e.g. CRD, RBAC etc.
manifests: controller-gen
	$(CONTROLLER_GEN) $(CRD_OPTIONS) rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases

# Generate template
template: manifests
	kustomize build config/crd > template.yaml
	echo "---" >> template.yaml
	kustomize build config/default >> template.yaml

# Run go fmt against code
fmt:
	go fmt ./...

# Run go vet against code
vet:
	go vet ./...

# Generate code
generate: controller-gen
#	$(CONTROLLER_GEN) object:headerFile=./hack/boilerplate.go.txt paths="./..."
	$(CONTROLLER_GEN) rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases

# Build the docker image
docker-build: test
	docker build . -t ${IMG}

# Push the docker image
docker-push:
	docker push ${IMG}

# find or download controller-gen
# download controller-gen if necessary
controller-gen:
ifeq (, $(shell which controller-gen))
	go get sigs.k8s.io/controller-tools/cmd/controller-gen@v0.8.0
CONTROLLER_GEN=$(GOBIN)/controller-gen
else
CONTROLLER_GEN=$(shell which controller-gen)
endif


##@ Build Dependencies

## Location to install dependencies to
#LOCALBIN ?= $(shell pwd)/bin
#$(LOCALBIN): ## Ensure that the directory exists
#	mkdir -p $(LOCALBIN)

## Tool Binaries
#KUSTOMIZE ?= $(LOCALBIN)/kustomize
#CONTROLLER_GEN ?= $(LOCALBIN)/controller-gen

## Tool Versions
#KUSTOMIZE_VERSION ?= v3.8.7
#CONTROLLER_TOOLS_VERSION ?= v0.8.0

#KUSTOMIZE_INSTALL_SCRIPT ?= "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"
#.PHONY: kustomize
#kustomize: $(KUSTOMIZE) ## Download kustomize locally if necessary.
#$(KUSTOMIZE):
#    curl -s $(KUSTOMIZE_INSTALL_SCRIPT) | bash -s -- $(subst v,,$(KUSTOMIZE_VERSION)) $(LOCALBIN)

#.PHONY: controller-gen
#controller-gen: $(CONTROLLER_GEN) ## Download controller-gen locally if necessary.
#$(CONTROLLER_GEN):
#    GOBIN=$(LOCALBIN) go install sigs.k8s.io/controller-tools/cmd/controller-gen@$(CONTROLLER_TOOLS_VERSION)

# Build ADCS simulator
sim:
	go build -o bin/adcs-sim test/adcs-sim/main.go

sim-install: sim
	cp bin/adcs-sim /usr/local/bin
	mkdir -p /usr/local/adcs-sim
	cp -R test/adcs-sim/ca test/adcs-sim/templates /usr/local/adcs-sim
